---
title: "Hierarchical clustering"
output: html_notebook
author: "MaggieMCKO"
date: "12/25/2020"
---

This [R Markdown](http://rmarkdown.rstudio.com) Notebook contain codes for reproducing Fig.1 of the [sex difference manuscript] ().

### Fig. 1B
```{r}
library(tidyverse) # v.1.3.0

## load data
csv_path =  paste0(getwd(), "/data/SampleTraits.csv")
sub = read_csv(csv_path)

csv_path = paste0(getwd(), "/data/Normalized_gene_expression.csv")
collapse_gene = read_csv(csv_path)

## get HVC samples
sub = subset(sub, su = Tissue == "HVC")

## take gene data of wanted samples
su_samples = sub$NewName # 65
# names(collapse_gene)
ind_col = sapply(su_samples, function(s){which(names(collapse_gene) == s)}) # 65

## transpose
gene_transpose = collapse_gene[, unlist(ind_col)] %>% t() 
colnames(gene_transpose) = collapse_gene$group

# calculate average gene expression levels per groups
dim(gene_transpose) #   65 12360
gene_transpose[1:3, 1:3]

collapse_gene_groups = gene_transpose %>% as_tibble(rownames = "Group") %>%
  mutate(Group = gsub("_\\d+[RL]*", "", Group),
         Group = gsub("-2", "", Group))  %>%
  group_by(Group) %>% summarise_at(vars(A1CF:ZZZ3), mean, na.rm = TRUE)
collapse_gene_groups[1:5, 1:5]


# Turn to matrix for clustering
dat = t(collapse_gene_groups[, -c(1)])
dim(dat) # 12360    11
dat[1:3, 1:3]
colnames(dat) =  collapse_gene_groups$Group

cor = cor(dat, use = "pairwise.complete.obs", method = "spearman") 
sampleTree.eucli.a = hclust(dist(1-cor, method = "euclidean"), method = "average"); 
plot(sampleTree.eucli.a, main = "", sub="", ylab="dissimilarity", xlab="", ylim=c(0,1), yaxs="i")

```

### Fig. S2. HVC
```{r}
library(tidyverse) # v.1.3.0
library(dendextend) # 1.14.0

## load data
csv_path =  paste0(getwd(), "/data/SampleTraits.csv")
sub = read_csv(csv_path)

csv_path = paste0(getwd(), "/data/Normalized_gene_expression.csv")
collapse_gene = read_csv(csv_path)

## get HVC samples
sub = subset(sub, su = Tissue == "HVC")

## take gene data of wanted samples
su_samples = sub$NewName # 65
# names(collapse_gene)
ind_col = sapply(su_samples, function(s){which(names(collapse_gene) == s)}) # 65

dat = collapse_gene[, unlist(ind_col)] 
dim(dat) # 12360    65

## clustering
cor = cor(dat, use = "pairwise.complete.obs", method = "spearman") 
sampleTree.eucli.a = hclust(dist(1-cor, method = "euclidean"), method = "average"); 
# plot(sampleTree.eucli.a, main = "", sub="", ylab="dissimilarity", xlab="", ylim=c(0,1), yaxs="i")

```

```{r, fig.height = 10, fig.width = 6}
## plotting using dendextend package
dend = sampleTree.eucli.a %>% as.dendrogram
# plot(dend)

## get labels
lab = labels(dend)
label_col = rep("blue", length(lab))
ind = grep("f", lab)
label_col[ind] = "red"

# dend %>% set("labels_col", label_col) %>% plot

ind_fw = grep("FW", lab)
ind_cb = grep("CB", lab)
can_or = "#ff6600ff"
fw_gr = "#338000ff"
cb_bl = "#0044aaff"
branch_col = rep(can_or, length(lab))
branch_col[ind_fw] = fw_gr
branch_col[ind_cb] = cb_bl


par(mar=c(4, 0, 0, 8))
par(mgp=c(2.5,1,.5)) # axis title, axis labels and axis line.
dend %>% set("labels_cex", 0.8) %>% 
  set("leaves_col", c(label_col)) %>% set("leaves_pch", 19) %>%
  color_branches(col = branch_col) %>%
  plot(xlab="dissimilarity", horiz = TRUE, cex.axis= 0.8, cex.lab = 0.8)
```

### Fig. S3. Entopallium
```{r}
library(tidyverse) # v.1.3.0
library(dendextend) # 1.14.0

## load data
csv_path =  paste0(getwd(), "/data/SampleTraits.csv")
sub = read_csv(csv_path)

csv_path = paste0(getwd(), "/data/Normalized_gene_expression.csv")
collapse_gene = read_csv(csv_path)

## get HVC samples
sub = subset(sub, su = Tissue == "Ento")

## take gene data of wanted samples
su_samples = sub$NewName # 65
# names(collapse_gene)
ind_col = sapply(su_samples, function(s){which(names(collapse_gene) == s)}) # 65

dat = collapse_gene[, unlist(ind_col)] 
dim(dat) # 12360    65

## clustering
cor = cor(dat, use = "pairwise.complete.obs", method = "spearman") 
sampleTree.eucli.a = hclust(dist(1-cor, method = "euclidean"), method = "average"); 
# plot(sampleTree.eucli.a, main = "", sub="", ylab="dissimilarity", xlab="", ylim=c(0,1), yaxs="i")

```

```{r, fig.height = 10, fig.width = 6}
## plotting using dendextend package
dend = sampleTree.eucli.a %>% as.dendrogram
# plot(dend)

## get labels
lab = labels(dend)
label_col = rep("blue", length(lab))
ind = grep("f", lab)
label_col[ind] = "red"

# dend %>% set("labels_col", label_col) %>% plot

ind_fw = grep("FW", lab)
ind_cb = grep("CB", lab)
can_or = "#ff6600ff"
fw_gr = "#338000ff"
cb_bl = "#0044aaff"
branch_col = rep(can_or, length(lab))
branch_col[ind_fw] = fw_gr
branch_col[ind_cb] = cb_bl


par(mar=c(4, 0, 0, 8))
par(mgp=c(2.5,1,.5)) # axis title, axis labels and axis line.
dend %>% set("labels_cex", 0.8) %>% 
  set("leaves_col", c(label_col)) %>% set("leaves_pch", 19) %>%
  color_branches(col = branch_col) %>%
  plot(xlab="dissimilarity", horiz = TRUE, cex.axis= 0.8, cex.lab = 0.8)
```